### ISSUE TITLE
Added Concept scheme and two test concepts. The UI was not updated to show the actual concept names

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1356]
@Lomilar 
Added concept scheme:  ce-3f0a4095-c455-4209-acfe-ac0486f74e78
On click of Done, the UI still shows the default name of **New Concept Scheme**.
I created two concepts Concept 1, and Concept 2, but the UI shows the default names of **New Concept**.

**Comment by mparsons-ce** [comment]
Also on attempts to edit the concept scheme, I would get a similar error to the progression model issue: that publication status must be selected, where it already is. 
![image](https://github.com/cassproject/cass-editor/assets/58825866/244de987-aee8-4513-a19e-31b98c6f14a0)

**Comment by Lomilar** [comment]
This still can occur, but clicking on and then off the box can clear the issue now. Leaving this open.

**Comment by winonadeb** [comment]
since there is a workaround, perhaps this is not a blocker just a bug?

**Comment by sedula27** [comment]
The save/update names works on production, but sandbox remains the same.

Issue with the required fields(Description/Publication Status)  highlighted even though they are filled still persists

**Comment by sedula27** [comment]
Issue with the required fields(Description/Publication Status) highlighted even though they are filled, this is not a consistent issue

**Comment by miledivovic** [comment]
@sedula27 I'm trying to replicate this issue on https://sandbox.credentialengine.org/ currently and am unable to do so. This may already be fixed, can you confirm if this is the case?

**Comment by sedula27** [comment]
@miledivovic  The issue with adding a concept scheme/Progression model right now is, it does not recognize the Publication status type even though there is a value there, refer to https://github.com/cassproject/cass-editor/issues/1346. The current work around for adding a concept scheme without the publication status type is 
**_This still can occur, but clicking on and then off the box can clear the issue now. Leaving this open._**  as Fritz mentioned above

**Comment by miledivovic** [comment]
@sedula27 I'm not able to reproduce the issue with the publication status type either, the concept scheme is able to save without needing to click on and off the box

**Comment by sedula27** [comment]
@miledivovic  I did try just now and I was not able to add a concept scheme without publication status type throwing an error, refer screen recording attached
 

https://github.com/cassproject/cass-editor/assets/93455942/bf53c4d9-41d6-4d28-99af-e864bb0a5e15

**Comment by miledivovic** [comment]
@sedula27 Interesting, I wonder if maybe there is some caching going on resulting in you not being given the most recent version of the cass editor... because this exact scenario is working fine for me. Could you try to reproduce this is in an incognito window to rule out caching as the issue?

**Comment by sedula27** [comment]
Thanks @miledivovic This works when I tried it in my incognito window and my browser after clearing cache.

**Comment by miledivovic** [comment]
@sedula27 Hmm thats strange, for me the progression models are also working normally

**Comment by sedula27** [comment]
@miledivovic  When I try the same now for a concept scheme I do see the publication status error

**Comment by sedula27** [comment]
Error in the console 
main.js:39 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': The provided value is not of type '(record<ByteString, ByteString> or sequence<sequence<ByteString>>)'.
    at _callee$ (main.js:39:36)
    at tryCatch (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at editor.js:284:13

**Comment by sedula27** [comment]
CORS error on console
vue.runtime.esm.js:3065 DOMException: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "https://cass.credentialengine.org" from accessing a cross-origin frame.
    at VueComponent.initializeApp (https://cass.credentialengine.org/cass-editor/js/app.d1e69620.js:3689:37)
    at VueComponent.$route (https://cass.credentialengine.org/cass-editor/js/app.d1e69620.js:5426:14)
    at invokeWithErrorHandling (https://cass.credentialengine.org/cass-editor/js/chunk-vendors.4d1b7240.js:38297:30)
    at push.2b0e.Watcher.run (https://cass.credentialengine.org/cass-editor/js/chunk-vendors.4d1b7240.js:38798:21)
    at flushSchedulerQueue (https://cass.credentialengine.org/cass-editor/js/chunk-vendors.4d1b7240.js:39324:17)
    at Array.<anonymous> (https://cass.credentialengine.org/cass-editor/js/chunk-vendors.4d1b7240.js:38421:20)
    at flushCallbacks (https://cass.credentialengine.org/cass-editor/js/chunk-vendors.4d1b7240.js:38343:18)

**Comment by miledivovic** [comment]
@sedula27 This should be fixed now on sandbox

**Comment by sedula27** [comment]
This is fixed on sandbox and has been verified
