### ISSUE TITLE
Uncaught RuntimeException while searching

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#620]
version 1.2.26, on dev

Stack trace:
Uncaught RuntimeException {detailMessage: "Incompatible type: https://schema.cassproject.org/0.3/Competency", message: "Incompatible type: https://schema.cassproject.org/0.3/Competency", cause: undefined, stack: "Error: Incompatible type: https://schema.cassproje…ub.io/cass-editor/js/cass/cass-editor.js:43133:17"}cause: undefineddetailMessage: "Incompatible type: https://schema.cassproject.org/0.3/Competency"message: "Incompatible type: https://schema.cassproject.org/0.3/Competency"stack: "Error: Incompatible type: https://schema.cassproject.org/0.3/Competency↵    at RuntimeException.Exception [as constructor] (https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:41839:12)↵    at new RuntimeException (https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:41845:12)↵    at EcEncryptedValue.prototype.copyFrom (https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:87855:20)↵    at Function.constructor.fromEncryptedValueAsync (https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:91087:13)↵    at https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:93443:38↵    at https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:43557:13↵    at https://cassproject.github.io/cass-editor/js/cass/cass-editor.js:43133:17"__proto__: Exception

prototype.copyFrom | @ | cass-editor.js:87855
  | constructor.fromEncryptedValueAsync | @ | cass-editor.js:91087
  | (anonymous) | @ | cass-editor.js:93443
  | (anonymous) | @ | cass-editor.js:43557
  | (anonymous) | @ | cass-editor.js:43133
  | setTimeout (async) |   |  
  | constructor.immediate | @ | cass-editor.js:43131
  | prototype.executeSet | @ | cass-editor.js:43556
  | prototype.eachSet | @ | cass-editor.js:43543
  | (anonymous) | @ | cass-editor.js:93442
  | prototype.handleSearchResults | @ | cass-editor.js:93352
  | (anonymous) | @ | cass-editor.js:92903
  | (anonymous) | @ | cass-editor.js:42818
  | xhr.onreadystatechange | @ | cass-editor.js:42648
  | XMLHttpRequest.send (async) |   |  
  | constructor.postInner | @ | cass-editor.js:42680
  | constructor.postExpectingObject | @ | cass-editor.js:42592
  | (anonymous) | @ | cass-editor.js:92896
  | (anonymous) | @ | cass-editor.js:90129
  | prototype.each | @ | cass-editor.js:43521
  | constructor.signatureSheetAsync | @ | cass-editor.js:90111
  | prototype.searchWithParams | @ | cass-editor.js:92894
  | constructor.searchAs | @ | cass-editor.js:93439
  | constructor.search | @ | cass-editor.js:95433
  | frameworkSearchByCompetency | @ | cass-editor.js:108297
  | searchFrameworks | @ | cass-editor.js:108089
  | (anonymous) | @ | cass-editor.js:108362
  | dispatch | @ | cass-editor.js:3
  | q.handle | @ | cass-editor.js:3

**Comment by woodkri** [comment]
This was caused by https://github.com/Eduworks/ec/issues/67, no longer happening in version 1.2.27
